import { getDatabaseProvider } from "./provider";
import * as sqliteApp from "./app.schema";
import * as sqliteAudit from "./audit.schema";
import * as sqliteSam from "./sam.schema";
import * as sqliteAuth from "./better-auth-schema";
import * as sqliteBilling from "./billing.schema";
import * as sqliteGa4 from "./ga4.schema";
import * as sqliteGsc from "./gsc.schema";
import * as sqliteTelemetry from "./telemetry.schema";
import * as sqliteLocalSeo from "./local-seo.schema";
import * as sqliteGoogleAds from "./google-ads.schema";
import * as sqliteReports from "./report.schema";
import * as sqliteDisavow from "./disavow.schema";
import * as sqliteAiVisibility from "./ai-visibility.schema";
import * as sqliteRankTracking from "./rank-tracking.schema";
import * as sqliteChangeEvents from "./change-events.schema";
import * as sqliteDomainResearch from "./domain-research.schema";
import * as pgApp from "./pg/app.schema";
import * as pgAudit from "./pg/audit.schema";
import * as pgSam from "./pg/sam.schema";
import * as pgAuth from "./pg/better-auth-schema";
import * as pgBilling from "./pg/billing.schema";
import * as pgGa4 from "./pg/ga4.schema";
import * as pgGsc from "./pg/gsc.schema";
import * as pgTelemetry from "./pg/telemetry.schema";
import * as pgLocalSeo from "./pg/local-seo.schema";
import * as pgGoogleAds from "./pg/google-ads.schema";
import * as pgReports from "./pg/report.schema";
import * as pgDisavow from "./pg/disavow.schema";
import * as pgAiVisibility from "./pg/ai-visibility.schema";
import * as pgRankTracking from "./pg/rank-tracking.schema";
import * as pgChangeEvents from "./pg/change-events.schema";
import * as pgDomainResearch from "./pg/domain-research.schema";

// Canonical schema barrel. Repositories import their tables from here and the
// provider-aware `db` from "@/db", so each repository is written ONCE for both
// backends.
//
// The TYPE identity is the SQLite definitions; the runtime VALUES are whichever
// provider is active. `schema-parity.test.ts` asserts the two dialect schemas
// are structurally interchangeable (same tables/columns/nullability/PKs/unique
// indexes), which is what makes the single cast below sound. The Postgres
// schema is the one structural artifact NOT regenerated by `db:generate`, so the
// parity test is its drift guard.
type AppSchema = typeof sqliteApp &
  typeof sqliteAudit &
  typeof sqliteSam &
  typeof sqliteAuth &
  typeof sqliteBilling &
  typeof sqliteGa4 &
  typeof sqliteGsc &
  typeof sqliteTelemetry &
  typeof sqliteLocalSeo &
  typeof sqliteGoogleAds &
  typeof sqliteReports &
  typeof sqliteDisavow &
  typeof sqliteAiVisibility &
  typeof sqliteRankTracking &
  typeof sqliteChangeEvents &
  typeof sqliteDomainResearch;

const runtimeSchema =
  getDatabaseProvider() === "postgres"
    ? {
        ...pgApp,
        ...pgAudit,
        ...pgSam,
        ...pgAuth,
        ...pgBilling,
        ...pgGa4,
        ...pgGsc,
        ...pgTelemetry,
        ...pgLocalSeo,
        ...pgGoogleAds,
        ...pgReports,
        ...pgDisavow,
        ...pgAiVisibility,
        ...pgRankTracking,
        ...pgChangeEvents,
        ...pgDomainResearch,
      }
    : {
        ...sqliteApp,
        ...sqliteAudit,
        ...sqliteSam,
        ...sqliteAuth,
        ...sqliteBilling,
        ...sqliteGa4,
        ...sqliteGsc,
        ...sqliteTelemetry,
        ...sqliteLocalSeo,
        ...sqliteGoogleAds,
        ...sqliteReports,
        ...sqliteDisavow,
        ...sqliteAiVisibility,
        ...sqliteRankTracking,
        ...sqliteChangeEvents,
        ...sqliteDomainResearch,
      };

// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- guarded by schema-parity.test.ts
const schema = runtimeSchema as unknown as AppSchema;

export const {
  userOnboardingAnswers,
  projects,
  memberAccessProfiles,
  projectMemberAccess,
  savedKeywords,
  savedKeywordTags,
  savedKeywordTagAssignments,
  keywordMetrics,
  rankTrackingConfigs,
  rankTrackingKeywords,
  rankCheckRuns,
  rankSnapshots,
  organizationActivationState,
  projectActivationState,
  backlinkSnapshots,
  audits,
  auditPages,
  auditIssues,
  auditLighthouseResults,
  auditSchedules,
  samSessions,
  samProjectMemory,
  user,
  session,
  account,
  apikey,
  verification,
  organization,
  member,
  invitation,
  billingCustomerStatus,
  ga4Connections,
  gscConnections,
  googleAdsConnections,
  reportSettings,
  reportSections,
  reportRuns,
  reportCommentaryItems,
  reportDeliveryProfiles,
  reportDeliveryProfileSections,
  reportRecipients,
  reportArtifacts,
  reportShareLinks,
  reportDeliveries,
  projectChangeEvents,
  projectChangeEventStates,
  backlinkDisavowEntries,
  telemetryState,
  localBusinessProfiles,
  localListingConnections,
  geoGridConfigs,
  geoGridRuns,
  geoGridCells,
  citationAuditRuns,
  citationObservations,
  aiVisibilityConfigs,
  aiVisibilityConfigProviders,
  aiVisibilityPrompts,
  aiVisibilityRuns,
  aiVisibilityObservations,
  aiVisibilityCitations,
  domainBrandTokens,
  domainResearchSnapshots,
  domainResearchPages,
  domainSerpFeatureMonths,
} = schema;
