import {
  deleteSavedKeywordTag,
  getSavedKeywords,
  getSerpAnalysis,
  removeSavedKeywords,
  research,
  saveKeywords,
  exportSavedKeywords,
  updateSavedKeywordTag,
  updateSavedKeywordTags,
  refreshSavedKeywordMetrics,
} from "@/server/features/keywords/services/research";
import {
  estimateKeywordMagic,
  exportKeywordMagic,
  getKeywordMagicPage,
  listKeywordMagicHistory,
  refreshKeywordMagicMetrics,
  runKeywordMagic,
  saveKeywordMagicSelection,
} from "@/server/features/keywords/services/magic/KeywordMagicService";

export const KeywordResearchService = {
  research,
  getSerpAnalysis,
  saveKeywords,
  getSavedKeywords,
  exportSavedKeywords,
  updateSavedKeywordTags,
  updateSavedKeywordTag,
  deleteSavedKeywordTag,
  removeSavedKeywords,
  refreshSavedKeywordMetrics,
  estimateKeywordMagic,
  runKeywordMagic,
  getKeywordMagicPage,
  exportKeywordMagic,
  listKeywordMagicHistory,
  saveKeywordMagicSelection,
  refreshKeywordMagicMetrics,
} as const;
